# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "chef/centos-7.0"
#  config.vm.network "forwarded_port", guest: 8080, host: 8080
#  config.vm.network "forwarded_port", guest: 9990, host: 9990
#  config.vm.network "forwarded_port", guest: 80, host: 1080
	config.vm.network "private_network", ip: "192.168.100.100"
end
